version: "3.9"
services:
  backend.ai.app.svc.local:
    container_name: backend
    volumes:
      # below line for development purposes only. Enabling developer to see changes instantely without the need to rebuild
      - ./src:/app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./src/conf/app.env
    restart: always
  backend.ai.app.db.local:
    container_name: database
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - devops/db/db.env
    ports:
      - "5433:5432"
networks:
  default:
    name: app_custom_network

volumes:
  app:
  postgres_data: