"""first initialization

Revision ID: 1_8257cac084f1
Revises: 
Create Date: 2023-07-04 12:39:48.119375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1_8257cac084f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app1_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app1_users_email'), 'app1_users', ['email'], unique=True)
    op.create_index(op.f('ix_app1_users_id'), 'app1_users', ['id'], unique=False)
    op.create_table('app1_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['app1_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app1_items_id'), 'app1_items', ['id'], unique=False)
    op.create_index(op.f('ix_app1_items_title'), 'app1_items', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app1_items_title'), table_name='app1_items')
    op.drop_index(op.f('ix_app1_items_id'), table_name='app1_items')
    op.drop_table('app1_items')
    op.drop_index(op.f('ix_app1_users_id'), table_name='app1_users')
    op.drop_index(op.f('ix_app1_users_email'), table_name='app1_users')
    op.drop_table('app1_users')
    # ### end Alembic commands ###
