"""add first_name

Revision ID: 2_3f1adbd9fc04
Revises: 1_8257cac084f1
Create Date: 2023-07-04 12:56:12.074118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2_3f1adbd9fc04'
down_revision = '1_8257cac084f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app1_users', sa.Column('first_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app1_users', 'first_name')
    # ### end Alembic commands ###
