"""email not nullable

Revision ID: 4_d184ac9172bf
Revises: 3_02d8ce465cd5
Create Date: 2023-07-04 13:22:43.201960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4_d184ac9172bf'
down_revision = '3_02d8ce465cd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app1_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app2_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app2_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app1_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
