"""add user model

Revision ID: 5_7486c7c9cf43
Revises: 4_d184ac9172bf
Create Date: 2023-07-08 15:03:47.751577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5_7486c7c9cf43'
down_revision = '4_d184ac9172bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iam_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_iam_users_id'), 'iam_users', ['id'], unique=False)
    op.create_table('iam_session_log',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['iam_users.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iam_session_log')
    op.drop_index(op.f('ix_iam_users_id'), table_name='iam_users')
    op.drop_table('iam_users')
    # ### end Alembic commands ###
